name: myFirstWorkflow
on: 
  push:
    paths-ignore: 
      .github/**    
    branches: 
      - master
  workflow_dispatch:
    inputs: 
      homedrive:
        description: 'The home drive on this machine'
        required: true
      logLevel:
        description: 'Log Detail Level'
        default: 'info'
        type: choice
        options:
        -  info
        -  warning
        -  error
        -  debug
  schedule:
    - cron: '45 19 * * 4'
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "👋 Hello World!"
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in the repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          du -a
          
