name: myFirstWorkflow
on: 
  push:
    branches: 
      - master
      - environment_hot_cold_test
  workflow_dispatch:
    inputs:
      is_paused:
        description: 'Is this workflow paused?'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
#      homedrive:
#        description: 'The home drive on this machine'
#        required: true
      logLevel:
        description: 'Log Detail Level'
        default: 'info'
        type: choice
        options:
          -  info
          -  warning
          -  error
          -  debug
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "👋 Hello World!"
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: List files in the repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          du -a
      - name: Set Environment
        id: set-environment
        shell: bash
        run: |
          if [ "${{ github.event.inputs.is_paused }}" == "true" ]; then
            ENVIRONMENT_NAME="Approvals Required - Pause"
          else
            ENVIRONMENT_NAME="No Approvals No Pause"
          fi
          echo "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" >> $GITHUB_ENV
          
  GateWithEnvironment:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    environment: ${{ env.ENVIRONMENT_NAME }}
    steps:
      - run: |
          if [ "${{ event.inputs.is_paused }}" == "true" ]; then
            echo "This job paused and required approval to proceed."
          else
            echo "This job will run without approval."
          fi
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: List files in the repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          du -a


